/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import frecuencia.Gestor;
import frecuencia.HerramientasColor;
import frecuencia.NumeroComplejo;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author fran_
 */
public class JInternalFrameFrecuenciaYInversa extends javax.swing.JInternalFrame {

    private JInternalFrameImagen internal;
    private Image imagenOriginal;

    /**
     * Creates new form JInternalFrameFrecuenciaYInversa
     */
    public JInternalFrameFrecuenciaYInversa(JInternalFrameImagen internal) {
        this.internal = internal;
        initComponents();
        
        this.jLabelFrecuencia.setVisible(false);
        this.jLabelInversa.setVisible(false);

        this.imagenOriginal = herramientas.HerramientasImagen.copiarImagen(internal.getImagenOriginal());
        
        BufferedImage Rimag = herramientas.HerramientasImagen.toBufferedImage(imagenOriginal);
        Gestor gestor = new Gestor(Rimag);

        this.jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jRadioButtonRojo.isSelected()) {
                    
                    BufferedImage biRes = gestor.obtenerImagenFrecuencias( true, "ROJO");
                    BufferedImage res = gestor.obtenerImagenEspacial("ROJO");
                    jLabelFrecuencia.setVisible(true);
                    jLabelInversa.setVisible(true);
                    Image iRes = herramientas.HerramientasImagen.toImage(biRes);
                    jLabelFrecuencia.setIcon(new ImageIcon(iRes));
                    jLabelFrecuencia.setSize(iRes.getWidth(internal), iRes.getHeight(internal));

                    Image iRes2 = herramientas.HerramientasImagen.toImage(res);
                    jLabelInversa.setIcon(new ImageIcon(iRes2));
                    jLabelFrecuencia.setSize(iRes.getWidth(null), iRes.getHeight(null));

                } else if (jRadioButtonGreen.isSelected()) {
                    BufferedImage biRes = gestor.obtenerImagenFrecuencias(true, "VERDE");
                    BufferedImage res = gestor.obtenerImagenEspacial("VERDE");
                    jLabelFrecuencia.setVisible(true);
                    jLabelInversa.setVisible(true);
                    Image iRes = herramientas.HerramientasImagen.toImage(biRes);
                    jLabelFrecuencia.setIcon(new ImageIcon(iRes));
                    jLabelFrecuencia.setSize(iRes.getWidth(internal), iRes.getHeight(internal));

                    Image iRes2 = herramientas.HerramientasImagen.toImage(res);
                    jLabelInversa.setIcon(new ImageIcon(iRes2));
                    jLabelFrecuencia.setSize(iRes.getWidth(null), iRes.getHeight(null));
                } else if (jRadioButtonAzul.isSelected()) {
                    BufferedImage biRes = gestor.obtenerImagenFrecuencias(true, "AZUL");
                    BufferedImage res = gestor.obtenerImagenEspacial("AZUL");
                    jLabelFrecuencia.setVisible(true);
                    jLabelInversa.setVisible(true);
                    Image iRes = herramientas.HerramientasImagen.toImage(biRes);
                    jLabelFrecuencia.setIcon(new ImageIcon(iRes));
                    jLabelFrecuencia.setSize(iRes.getWidth(internal), iRes.getHeight(internal));

                    Image iRes2 = herramientas.HerramientasImagen.toImage(res);
                    jLabelInversa.setIcon(new ImageIcon(iRes2));
                    jLabelFrecuencia.setSize(iRes.getWidth(null), iRes.getHeight(null));
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonGreen = new javax.swing.JRadioButton();
        jRadioButtonRojo = new javax.swing.JRadioButton();
        jRadioButtonAzul = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabelInversa = new javax.swing.JLabel();
        jLabelFrecuencia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);

        jRadioButtonGreen.setText("Green");

        jRadioButtonRojo.setText("Rojo");

        jRadioButtonAzul.setText("Azul");

        jButton1.setText("Start");

        jLabel1.setText("Espectro:");

        jLabel2.setText("Inversa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButtonRojo)
                        .addGap(66, 66, 66)
                        .addComponent(jRadioButtonAzul))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInversa, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonGreen)
                        .addGap(88, 88, 88)
                        .addComponent(jButton1))
                    .addComponent(jLabel2))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonGreen)
                    .addComponent(jRadioButtonAzul)
                    .addComponent(jRadioButtonRojo)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInversa, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFrecuencia;
    private javax.swing.JLabel jLabelInversa;
    private javax.swing.JRadioButton jRadioButtonAzul;
    private javax.swing.JRadioButton jRadioButtonGreen;
    private javax.swing.JRadioButton jRadioButtonRojo;
    // End of variables declaration//GEN-END:variables
}
