/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import espacial.SalyPimienta;
import java.awt.Image;
import java.awt.image.BufferedImage;

/**
 *
 * @author fran_
 */
public class JInternalFrameSalPimienta extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameSalPimienta
     */
    private JInternalFrameImagen internal;
    private Image imagenOriginal;

    public JInternalFrameSalPimienta(JInternalFrameImagen internal) {
        this.internal = internal;
        initComponents();
        

        this.imagenOriginal = herramientas.HerramientasImagen.copiarImagen(internal.getImagenOriginal());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderSal = new javax.swing.JSlider();
        jSliderMixta = new javax.swing.JSlider();
        jSliderPimienta = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();

        jSliderSal.setMajorTickSpacing(10);
        jSliderSal.setPaintLabels(true);
        jSliderSal.setPaintTicks(true);
        jSliderSal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSalStateChanged(evt);
            }
        });

        jSliderMixta.setMajorTickSpacing(10);
        jSliderMixta.setPaintLabels(true);
        jSliderMixta.setPaintTicks(true);
        jSliderMixta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderMixtaStateChanged(evt);
            }
        });

        jSliderPimienta.setMajorTickSpacing(10);
        jSliderPimienta.setPaintLabels(true);
        jSliderPimienta.setPaintTicks(true);
        jSliderPimienta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPimientaStateChanged(evt);
            }
        });

        jLabel1.setText("Ruido Sal");

        jLabel2.setText("Ruido Mixtas");

        jLabel3.setText("Ruido Pimienta");

        jCheckBox1.setText("Mixta");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Sal");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Pimienta");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox1)
                            .addGap(131, 131, 131)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox2)
                            .addGap(152, 152, 152)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderSal, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSliderMixta, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSliderPimienta, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBox3))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(193, 193, 193)
                    .addComponent(jLabel3)
                    .addContainerGap(216, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addGap(3, 3, 3)
                .addComponent(jSliderPimienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderMixta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(jLabel3)
                    .addContainerGap(187, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jSliderSalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSalStateChanged
        // TODO add your handling code here:
        jSliderSal.setVisible(false);
        if (jCheckBox1.isSelected()) {
            jSliderSal.setVisible(true);
            int u = jSliderSal.getValue();
            SalyPimienta m = new SalyPimienta();
            BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(imagenOriginal);
            bi = m.aplicarSal(imagenOriginal, u);
            Image nueva = herramientas.HerramientasImagen.toImage(bi);
            internal.setImagen(nueva);
        } else {
            jSliderSal.setVisible(false);
        }
    }//GEN-LAST:event_jSliderSalStateChanged

    private void jSliderPimientaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPimientaStateChanged
        // TODO add your handling code here:}
        jSliderPimienta.setVisible(false);
        if (jCheckBox2.isSelected()) {
            jSliderPimienta.setVisible(true);
            int p = jSliderPimienta.getValue();
            SalyPimienta m = new SalyPimienta();
            BufferedImage bip = herramientas.HerramientasImagen.toBufferedImage(imagenOriginal);
            bip = m.aplicarPimienta(imagenOriginal, p);
            Image nueva = herramientas.HerramientasImagen.toImage(bip);
            internal.setImagen(nueva);
        } else {
            jSliderPimienta.setVisible(false);
        }
    }//GEN-LAST:event_jSliderPimientaStateChanged

    private void jSliderMixtaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderMixtaStateChanged
        // TODO add your handling code here:
        jSliderMixta.setVisible(false);
        if (jCheckBox3.isSelected()) {
            jSliderMixta.setVisible(true);
            int mix = jSliderMixta.getValue();
            SalyPimienta m = new SalyPimienta();
            BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(imagenOriginal);
            bi = m.aplicarMixto(imagenOriginal, mix);
            Image nueva = herramientas.HerramientasImagen.toImage(bi);
            internal.setImagen(nueva);
        } else {
            jSliderMixta.setVisible(false);
        }
    }//GEN-LAST:event_jSliderMixtaStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider jSliderMixta;
    private javax.swing.JSlider jSliderPimienta;
    private javax.swing.JSlider jSliderSal;
    // End of variables declaration//GEN-END:variables
}
