/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import espacial.Expancion;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;

/**
 *
 * @author fran_
 */
public class JInternalFrameExpancion extends javax.swing.JInternalFrame {
    
    private JInternalFrameImagen internal;
    private Image imagenOriginal;
    /**
     * Creates new form JInternalFrameExpancion
     * @param internal
     */
    public JInternalFrameExpancion(JInternalFrameImagen internal) {
        initComponents();
        Expancion expa = new Expancion();
        this.internal = internal;
        this.imagenOriginal = herramientas.HerramientasImagen.copiarImagen(internal.getImagenOriginal());
        this.jButtonLine.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(imagenOriginal);
               
                int r1 = Integer.parseInt(jTextFieldR1.getText());
                int r2 = Integer.parseInt(jTextField3.getText());
                
                System.out.println("r1 "+r1);
                System.out.println("r2 " +r2);
                if(r1>r2){
                    bi = expa.expancionLine(r1,r2,imagenOriginal);
                    Image nueva = herramientas.HerramientasImagen.toImage(bi);
                    internal.setImagen(nueva);
                }else if(r1<r2){
                    bi = expa.expancionLine(r1, r2, imagenOriginal);
                    Image nueva = herramientas.HerramientasImagen.toImage(bi);
                    internal.setImagen(nueva);
                    
                }
                Image nueva = herramientas.HerramientasImagen.toImage(bi);
                
                internal.setImagen(nueva);
                
            }
        });
        this.jButtonLog.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(imagenOriginal);
                int u = jSliderLog.getValue();
                System.out.println("u "+u);
                bi = expa.expancionLog(u, imagenOriginal);
                Image nueva = herramientas.HerramientasImagen.toImage(bi);
                internal.setImagen(nueva);
            }
        });
        this.jButtonExp.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(imagenOriginal);
                int v = jSliderLog.getValue();
                System.out.println("v= " +v);
                bi = expa.expancionExp(v, imagenOriginal);
                Image nueva = herramientas.HerramientasImagen.toImage(bi);
                internal.setImagen(nueva);
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonLog = new javax.swing.JButton();
        jSliderLog = new javax.swing.JSlider();
        jButtonEcua = new javax.swing.JButton();
        jSliderExp = new javax.swing.JSlider();
        jButtonExp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonLine = new javax.swing.JButton();
        jTextFieldR1 = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setText("r1:");

        jLabel2.setText("r2:");

        jButtonLog.setText("Logaritmica");
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });

        jSliderLog.setMajorTickSpacing(10);
        jSliderLog.setMaximum(255);
        jSliderLog.setPaintLabels(true);
        jSliderLog.setPaintTicks(true);
        jSliderLog.setValue(10);

        jButtonEcua.setText("Ecualizacion");

        jSliderExp.setMajorTickSpacing(10);
        jSliderExp.setMaximum(255);
        jSliderExp.setPaintLabels(true);
        jSliderExp.setPaintTicks(true);
        jSliderExp.setValue(10);

        jButtonExp.setText("Exponencial");

        jLabel3.setText("Expancion del Histograma");

        jButtonLine.setText("Lineal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldR1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(71, 71, 71)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(jButtonLog))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(jButtonExp))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(jButtonEcua))))
                        .addGap(243, 243, 243))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonLine)
                        .addGap(299, 299, 299))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSliderLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jSliderExp, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addComponent(jButtonLine)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonLog)
                .addGap(18, 18, 18)
                .addComponent(jSliderLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButtonExp)
                .addGap(18, 18, 18)
                .addComponent(jSliderExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButtonEcua)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonLogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEcua;
    private javax.swing.JButton jButtonExp;
    private javax.swing.JButton jButtonLine;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider jSliderExp;
    private javax.swing.JSlider jSliderLog;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldR1;
    // End of variables declaration//GEN-END:variables
}
